<?php

namespace Tests\Feature\Cache\Redis;

use Illuminate\Cache\Repository;
use Illuminate\Support\Facades\Cache;
use Tests\Feature\Cache\CacheTestCase;

class RedisCacheTest extends CacheTestCase
{

    protected function laravelCache(): Repository
    {
        return Cache::store('redis');
    }

    protected function symfonyCache(): Repository
    {
        return Cache::store('symfony_redis');
    }

    public function test_add_does_not_add_if_ttl_is_zero()
    {
        parent::test_add_does_not_add_if_ttl_is_zero(); // TODO: Change the autogenerated stub
    }
}
